/** @type {import('next-sitemap').IConfig} */

const fs = require("fs");
const path = require("path");

// next-sitemap discovers URLs from the Next.js build manifest (every prerendered
// route). That correctly picks up all real content pages — /peptides/*,
// /supplements/*, /news/*, /compare/*, and every top-level page — automatically
// as new page folders are added, with no manual list to maintain. But the
// manifest ALSO contains per-route image endpoints and noindex/redirect routes
// that must never be in a sitemap. We strip those here.
//
// COUPON PAGES ARE THE EXCEPTION: their inclusion is driven by vendors.ts, NOT
// by the build manifest. Manifest-based discovery is implicit — if a vendor's
// route is momentarily absent from the manifest at generation time, it silently
// drops from the sitemap (this is what briefly happened to ascension-peptides).
// To make it deterministic, every /coupons/<slug> detail page is stripped from
// manifest discovery below (transform returns null) and re-added explicitly via
// additionalPaths from the vendor registry: an active (non-retired) vendor that
// has a real page dir is ALWAYS emitted; a retired one or a registry entry with
// no deployed page is NEVER emitted. vendors.ts is the single source of truth.

// { slug, retired }[] generated from src/data/vendors.ts by
// scripts/gen-vendor-slugs.mjs (runs in `npm run build` before next-sitemap).
const vendorRegistry = require("./src/data/vendors.slugs.json");

const COUPONS_DIR = path.join(__dirname, "src", "app", "coupons");
const hasCouponPage = (slug) =>
  fs.existsSync(path.join(COUPONS_DIR, slug, "page.tsx"));

// Active + deployed vendors -> the coupon URLs the sitemap explicitly emits.
// Presence check guards against a registry entry whose page isn't deployed
// (would otherwise emit a sitemap URL pointing at a 404).
const activeCouponSlugs = vendorRegistry
  .filter((v) => !v.retired && hasCouponPage(v.slug))
  .map((v) => v.slug);

// Retired vendors -> excluded (their page.tsx is kept on disk and 308-redirects
// to /coupons via next.config.js, so it stays in the manifest). Derived from the
// same registry so flipping `retired: true` de-sitemaps a vendor automatically.
const retiredCouponPaths = vendorRegistry
  .filter((v) => v.retired)
  .map((v) => `/coupons/${v.slug}`);

// Matches a coupon DETAIL page (/coupons/<slug>) but not the /coupons hub.
const COUPON_DETAIL = /^\/coupons\/[a-z0-9-]+$/;

// Per-route utility endpoints + icon routes: dropped at any depth.
const DROP_PATTERNS = [
  /\/opengraph-image$/,
  /\/twitter-image$/,
  /^\/(icon|apple-icon)(\.png)?$/,
];

// Exact paths to drop: noindex pages (must match the page's robots metadata).
// EVERY page carrying `robots: { index: false }` must be listed here — a noindex
// page in the sitemap is a mixed signal (crawl+index via sitemap, don't-index on
// arrival) and wastes crawl budget. /vendors + /vendor-testing-index were noindex
// but leaked into the sitemap until Aug 2026; keep this set in lockstep with the
// pages' robots metadata.
const DROP_EXACT = new Set([
  "/contact", // src/app/contact -> metadata.robots { index: false }
  "/vendors", // src/app/vendors -> metadata.robots { index: false } (thin directory duplicating /coupons)
  "/vendor-testing-index", // src/app/vendor-testing-index/layout -> { index: false } (under construction)
  "/prototype/profile", // design sandbox -> metadata.robots { index: false }
  "/prototype/logo", // logo comparison (dev) -> metadata.robots { index: false }
]);

// Price-comparison compound pages: <3 vendors are noindex,follow (see /prices/[compound]
// robots). Derived from src/data/prices.index.json (generated by scripts/price-pull/
// to_prices.py) so it can't drift from the render's ≥3-vendor ungating threshold.
const priceIndex = require("./src/data/prices.index.json");
const noindexPricePaths = new Set(
  priceIndex.filter((p) => !p.indexable).map((p) => `/prices/${p.slug}`),
);
const PRICE_DETAIL = /^\/prices\/[a-z0-9-]+$/;

// ── lastmod: DELIBERATELY ABSENT (do not re-add build-time or git-date lastmod) ──────────────
// next-sitemap's DEFAULT lastmod is BUILD TIME (autoLastmod: true) — every URL's lastmod bumps on
// every deploy even when the page didn't change, a noisy signal Google learns to discount. So we
// set `autoLastmod: false` and emit NO <lastmod> at all: an absent lastmod is neutral; a fake,
// always-fresh one is worse.
//
// A content-based lastmod (git last-commit date of each route's source/data files) was BUILT and
// REVERTED in Aug 2026 (see git history around this file + vercel.json). The reason it was dropped —
// do NOT rebuild it without solving this:
//
//   The un-shallow WORKED and the resolver RAN CORRECTLY. Verified from Vercel's build logs for
//   commit f83259a: the buildCommand's `git fetch --unshallow` succeeded, full git history was
//   available in CI, and the build emitted "content-lastmod: all 282 route(s) resolved to a git
//   date" — every route got a REAL git date, none fell back.
//
//   The dates were just FLAT. 282 lastmods resolved to only ~5 distinct timestamps, because the
//   dates block-date together two ways: (a) the ~111 coupon + price pages all derive from the SHARED
//   files src/data/vendors.ts and src/data/prices.generated.ts, so a single pull re-dates all of
//   them at once; and (b) git can't distinguish a substantive rewrite from a formatting pass, so any
//   sitewide sweep (prose/description passes) resets the date on every file it touches. ~5 dates
//   across 282 routes isn't granularity — it's an always-fresh signal that only meaningfully varies
//   for the self-contained pages (profiles/guides/news/compare). Not worth the CI prerequisite.
//
//   NOTE: earlier notes on this (and commit 4cf76bd's message) wrongly blamed a silently-failed
//   un-shallow / shallow `git log` returning the HEAD date. That was a misdiagnosis — the build logs
//   show the un-shallow worked. The real, and only, problem is the flatness above.

module.exports = {
  siteUrl: "https://profpeptide.com",
  generateRobotsTxt: true,
  trailingSlash: false,
  // Emit NO <lastmod> — see the note above module.exports. autoLastmod: false stops next-sitemap
  // from injecting the build-time default; nothing here re-adds one.
  autoLastmod: false,
  exclude: [
    // Legacy /research and /research/* -> 301 redirect to /peptides/* (next.config.js).
    // Canonical lives at /peptides/<slug>, which IS included.
    "/research",
    "/research/*",
    // Per-route OG/Twitter image endpoints (belt-and-suspenders with transform()).
    "/*/opengraph-image",
    "/*/twitter-image",
    // Retired vendors -> 308 redirect to /coupons (next.config.js). Derived from
    // vendors.ts `retired: true` so this can't drift from the registry.
    ...retiredCouponPaths,
    // Design sandbox (noindex, dev-only preview) — never in the sitemap.
    "/prototype",
    "/prototype/*",
  ],
  transform: async (config, path) => {
    if (DROP_EXACT.has(path)) return null;
    if (DROP_PATTERNS.some((re) => re.test(path))) return null;
    // Price compound pages with <3 vendors are noindex -> keep them out of the sitemap.
    // /prices (master) and the ≥3-vendor compound pages pass through.
    if (PRICE_DETAIL.test(path) && noindexPricePaths.has(path)) return null;
    // Coupon detail pages come from the vendor registry (additionalPaths), not
    // the manifest — drop the manifest copy so inclusion is deterministic and
    // never duplicated.
    if (COUPON_DETAIL.test(path)) return null;
    return {
      loc: path,
      changefreq: config.changefreq,
      priority: config.priority,
      // No lastmod (autoLastmod: false) — see the note above module.exports.
    };
  },
  additionalPaths: async (config) => [
    // /peptides and /supplements USED to be re-added here: reading `?category` off searchParams
    // opted them into DYNAMIC (ƒ) rendering, so next-sitemap's manifest crawl (static ○ routes
    // only) missed them. The category filter is now client-side (HubCategoryBrowser), so both
    // hubs prerender ○ and enter the manifest on their own — the explicit re-add is gone.
    ...activeCouponSlugs.map((slug) => ({
      loc: `/coupons/${slug}`,
      changefreq: config.changefreq,
      priority: config.priority,
      // No lastmod (autoLastmod: false) — see the note above module.exports.
    })),
  ],
};
