/** @type {import('next-sitemap').IConfig} */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// next-sitemap discovers URLs from the Next.js build manifest (every prerendered
// route). That correctly picks up all real content pages — /peptides/*,
// /supplements/*, /news/*, /compare/*, and every top-level page — automatically
// as new page folders are added, with no manual list to maintain. But the
// manifest ALSO contains per-route image endpoints and noindex/redirect routes
// that must never be in a sitemap. We strip those here.
//
// COUPON PAGES ARE THE EXCEPTION: their inclusion is driven by vendors.ts, NOT
// by the build manifest. Manifest-based discovery is implicit — if a vendor's
// route is momentarily absent from the manifest at generation time, it silently
// drops from the sitemap (this is what briefly happened to ascension-peptides).
// To make it deterministic, every /coupons/<slug> detail page is stripped from
// manifest discovery below (transform returns null) and re-added explicitly via
// additionalPaths from the vendor registry: an active (non-retired) vendor that
// has a real page dir is ALWAYS emitted; a retired one or a registry entry with
// no deployed page is NEVER emitted. vendors.ts is the single source of truth.

// { slug, retired }[] generated from src/data/vendors.ts by
// scripts/gen-vendor-slugs.mjs (runs in `npm run build` before next-sitemap).
const vendorRegistry = require("./src/data/vendors.slugs.json");

const COUPONS_DIR = path.join(__dirname, "src", "app", "coupons");
const hasCouponPage = (slug) =>
  fs.existsSync(path.join(COUPONS_DIR, slug, "page.tsx"));

// Active + deployed vendors -> the coupon URLs the sitemap explicitly emits.
// Presence check guards against a registry entry whose page isn't deployed
// (would otherwise emit a sitemap URL pointing at a 404).
const activeCouponSlugs = vendorRegistry
  .filter((v) => !v.retired && hasCouponPage(v.slug))
  .map((v) => v.slug);

// Retired vendors -> excluded (their page.tsx is kept on disk and 308-redirects
// to /coupons via next.config.js, so it stays in the manifest). Derived from the
// same registry so flipping `retired: true` de-sitemaps a vendor automatically.
const retiredCouponPaths = vendorRegistry
  .filter((v) => v.retired)
  .map((v) => `/coupons/${v.slug}`);

// Matches a coupon DETAIL page (/coupons/<slug>) but not the /coupons hub.
const COUPON_DETAIL = /^\/coupons\/[a-z0-9-]+$/;

// Per-route utility endpoints + icon routes: dropped at any depth.
const DROP_PATTERNS = [
  /\/opengraph-image$/,
  /\/twitter-image$/,
  /^\/(icon|apple-icon)(\.png)?$/,
];

// Exact paths to drop: noindex pages (must match the page's robots metadata).
// EVERY page carrying `robots: { index: false }` must be listed here — a noindex
// page in the sitemap is a mixed signal (crawl+index via sitemap, don't-index on
// arrival) and wastes crawl budget. /vendors + /vendor-testing-index were noindex
// but leaked into the sitemap until Aug 2026; keep this set in lockstep with the
// pages' robots metadata.
const DROP_EXACT = new Set([
  "/contact", // src/app/contact -> metadata.robots { index: false }
  "/vendors", // src/app/vendors -> metadata.robots { index: false } (thin directory duplicating /coupons)
  "/vendor-testing-index", // src/app/vendor-testing-index/layout -> { index: false } (under construction)
  "/prototype/profile", // design sandbox -> metadata.robots { index: false }
  "/prototype/logo", // logo comparison (dev) -> metadata.robots { index: false }
]);

// Price-comparison compound pages: <3 vendors are noindex,follow (see /prices/[compound]
// robots). Derived from src/data/prices.index.json (generated by scripts/price-pull/
// to_prices.py) so it can't drift from the render's ≥3-vendor ungating threshold.
const priceIndex = require("./src/data/prices.index.json");
const noindexPricePaths = new Set(
  priceIndex.filter((p) => !p.indexable).map((p) => `/prices/${p.slug}`),
);
const PRICE_DETAIL = /^\/prices\/[a-z0-9-]+$/;

// ── content-based lastmod ─────────────────────────────────────────────────────
// next-sitemap's default lastmod is BUILD TIME, so every URL's lastmod bumps on every deploy
// even when the page didn't change — a noisy signal Google learns to discount, which slows
// recrawl of pages that actually did change. Instead, derive each route's lastmod from the git
// last-commit date of the file(s) that actually produce its content.
//
// REQUIRES full git history at build time. Vercel clones shallow (~depth 10), so vercel.json's
// buildCommand runs `git fetch --unshallow` first. If history is still missing (shallow) or a file
// is untracked, gitDate() returns null and the route gets NO <lastmod> — we NEVER fall back to
// build time (that would reintroduce the exact noise this removes). Every skipped route is logged
// loudly at process exit, so an inert un-shallow is impossible to miss.
const SRC = path.join(__dirname, "src");
const _gitDateCache = new Map();
function gitDate(absFile) {
  if (_gitDateCache.has(absFile)) return _gitDateCache.get(absFile);
  let iso = null;
  if (fs.existsSync(absFile)) {
    try {
      const out = execSync(`git log -1 --format=%cI -- "${absFile}"`, {
        cwd: __dirname,
        stdio: ["ignore", "pipe", "ignore"],
      })
        .toString()
        .trim();
      if (out) iso = out; // empty when the file's last commit is beyond a shallow clone
    } catch {
      /* git absent / no history — leave null */
    }
  }
  _gitDateCache.set(absFile, iso);
  return iso;
}

// Route -> the source/data files whose git dates define when its content last changed.
function depsFor(routePath) {
  const s = (rel) => path.join(SRC, rel);
  let m;
  // Coupon detail: facts come from vendors.ts, the price grid from prices.generated.ts.
  if ((m = routePath.match(/^\/coupons\/([a-z0-9-]+)$/)))
    return [s(`app/coupons/${m[1]}/page.tsx`), s("data/vendors.ts"), s("data/prices.generated.ts")];
  if (routePath === "/coupons") return [s("app/coupons/page.tsx"), s("app/coupons/layout.tsx"), s("data/vendors.ts")];
  // Price detail pages share one template + one data file; they all change together on a pull.
  if (PRICE_DETAIL.test(routePath)) return [s("data/prices.generated.ts")];
  if (routePath === "/prices") return [s("app/prices/page.tsx"), s("data/prices.generated.ts")];
  // Hubs: the list changes when the category data (or the page shell) changes.
  if (routePath === "/peptides") return [s("app/peptides/page.tsx"), s("data/peptideCategories.ts")];
  if (routePath === "/supplements") return [s("app/supplements/page.tsx"), s("data/supplements.ts")];
  if (routePath === "/news") return [s("app/news/page.tsx"), s("data/news.ts")];
  if (routePath === "/best-peptide-vendors") return [s("app/best-peptide-vendors/page.tsx"), s("data/vendors.ts")];
  // Self-contained detail pages: content lives in the page's own file.
  if ((m = routePath.match(/^\/(peptides|supplements|guides|news|compare)\/([a-z0-9-]+)$/)))
    return [s(`app/${m[1]}/${m[2]}/page.tsx`)];
  if (routePath === "/") return [s("app/page.tsx")];
  // Generic top-level / nested static page: its own page.tsx (and layout.tsx where metadata lives).
  const seg = routePath.replace(/^\//, "");
  return [s(`app/${seg}/page.tsx`), s(`app/${seg}/layout.tsx`)];
}

const _lastmodSkipped = [];
let _lastmodResolved = 0;
function lastmodFor(routePath) {
  const dates = depsFor(routePath).map(gitDate).filter(Boolean);
  if (!dates.length) {
    _lastmodSkipped.push(routePath);
    return undefined; // loud gap, never build time
  }
  _lastmodResolved += 1;
  return dates.sort().at(-1); // ISO-8601 sorts chronologically; newest = the page's real last change
}

process.on("exit", () => {
  if (_lastmodSkipped.length) {
    console.warn(
      `\n[next-sitemap] content-lastmod: ${_lastmodResolved} route(s) got a real git date; ` +
        `${_lastmodSkipped.length} emitted NONE (no history / untracked):`,
    );
    console.warn("  " + _lastmodSkipped.sort().join("\n  "));
    console.warn("  If this is (nearly) EVERY route, the build's git clone is still shallow — check the un-shallow.");
  } else {
    console.log(`[next-sitemap] content-lastmod: all ${_lastmodResolved} route(s) resolved to a git date.`);
  }
});

module.exports = {
  siteUrl: "https://profpeptide.com",
  generateRobotsTxt: true,
  trailingSlash: false,
  // We supply lastmod ourselves from git history (see lastmodFor); disable the build-time default
  // so a route we can't date carries NO lastmod rather than today's date.
  autoLastmod: false,
  exclude: [
    // Legacy /research and /research/* -> 301 redirect to /peptides/* (next.config.js).
    // Canonical lives at /peptides/<slug>, which IS included.
    "/research",
    "/research/*",
    // Per-route OG/Twitter image endpoints (belt-and-suspenders with transform()).
    "/*/opengraph-image",
    "/*/twitter-image",
    // Retired vendors -> 308 redirect to /coupons (next.config.js). Derived from
    // vendors.ts `retired: true` so this can't drift from the registry.
    ...retiredCouponPaths,
    // Design sandbox (noindex, dev-only preview) — never in the sitemap.
    "/prototype",
    "/prototype/*",
  ],
  transform: async (config, path) => {
    if (DROP_EXACT.has(path)) return null;
    if (DROP_PATTERNS.some((re) => re.test(path))) return null;
    // Price compound pages with <3 vendors are noindex -> keep them out of the sitemap.
    // /prices (master) and the ≥3-vendor compound pages pass through.
    if (PRICE_DETAIL.test(path) && noindexPricePaths.has(path)) return null;
    // Coupon detail pages come from the vendor registry (additionalPaths), not
    // the manifest — drop the manifest copy so inclusion is deterministic and
    // never duplicated.
    if (COUPON_DETAIL.test(path)) return null;
    return {
      loc: path,
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: lastmodFor(path), // git date of the page's content sources (undefined if undatable)
    };
  },
  additionalPaths: async (config) => [
    // /peptides and /supplements USED to be re-added here: reading `?category` off searchParams
    // opted them into DYNAMIC (ƒ) rendering, so next-sitemap's manifest crawl (static ○ routes
    // only) missed them. The category filter is now client-side (HubCategoryBrowser), so both
    // hubs prerender ○ and enter the manifest on their own — the explicit re-add is gone.
    ...activeCouponSlugs.map((slug) => ({
      loc: `/coupons/${slug}`,
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: lastmodFor(`/coupons/${slug}`),
    })),
  ],
};
