/** @type {import('next-sitemap').IConfig} */

const fs = require("fs");
const path = require("path");

// next-sitemap discovers URLs from the Next.js build manifest (every prerendered
// route). That correctly picks up all real content pages — /peptides/*,
// /supplements/*, /news/*, /compare/*, and every top-level page — automatically
// as new page folders are added, with no manual list to maintain. But the
// manifest ALSO contains per-route image endpoints and noindex/redirect routes
// that must never be in a sitemap. We strip those here.
//
// COUPON PAGES ARE THE EXCEPTION: their inclusion is driven by vendors.ts, NOT
// by the build manifest. Manifest-based discovery is implicit — if a vendor's
// route is momentarily absent from the manifest at generation time, it silently
// drops from the sitemap (this is what briefly happened to ascension-peptides).
// To make it deterministic, every /coupons/<slug> detail page is stripped from
// manifest discovery below (transform returns null) and re-added explicitly via
// additionalPaths from the vendor registry: an active (non-retired) vendor that
// has a real page dir is ALWAYS emitted; a retired one or a registry entry with
// no deployed page is NEVER emitted. vendors.ts is the single source of truth.

// { slug, retired }[] generated from src/data/vendors.ts by
// scripts/gen-vendor-slugs.mjs (runs in `npm run build` before next-sitemap).
const vendorRegistry = require("./src/data/vendors.slugs.json");

const COUPONS_DIR = path.join(__dirname, "src", "app", "coupons");
const hasCouponPage = (slug) =>
  fs.existsSync(path.join(COUPONS_DIR, slug, "page.tsx"));

// Active + deployed vendors -> the coupon URLs the sitemap explicitly emits.
// Presence check guards against a registry entry whose page isn't deployed
// (would otherwise emit a sitemap URL pointing at a 404).
const activeCouponSlugs = vendorRegistry
  .filter((v) => !v.retired && hasCouponPage(v.slug))
  .map((v) => v.slug);

// Retired vendors -> excluded (their page.tsx is kept on disk and 308-redirects
// to /coupons via next.config.js, so it stays in the manifest). Derived from the
// same registry so flipping `retired: true` de-sitemaps a vendor automatically.
const retiredCouponPaths = vendorRegistry
  .filter((v) => v.retired)
  .map((v) => `/coupons/${v.slug}`);

// Matches a coupon DETAIL page (/coupons/<slug>) but not the /coupons hub.
const COUPON_DETAIL = /^\/coupons\/[a-z0-9-]+$/;

// Per-route utility endpoints + icon routes: dropped at any depth.
const DROP_PATTERNS = [
  /\/opengraph-image$/,
  /\/twitter-image$/,
  /^\/(icon|apple-icon)(\.png)?$/,
];

// Exact paths to drop: noindex pages (must match the page's robots metadata).
// EVERY page carrying `robots: { index: false }` must be listed here — a noindex
// page in the sitemap is a mixed signal (crawl+index via sitemap, don't-index on
// arrival) and wastes crawl budget. /vendors + /vendor-testing-index were noindex
// but leaked into the sitemap until Aug 2026; keep this set in lockstep with the
// pages' robots metadata.
const DROP_EXACT = new Set([
  "/contact", // src/app/contact -> metadata.robots { index: false }
  "/vendors", // src/app/vendors -> metadata.robots { index: false } (thin directory duplicating /coupons)
  "/vendor-testing-index", // src/app/vendor-testing-index/layout -> { index: false } (under construction)
  "/prototype/profile", // design sandbox -> metadata.robots { index: false }
  "/prototype/logo", // logo comparison (dev) -> metadata.robots { index: false }
]);

// Price-comparison compound pages: <3 vendors are noindex,follow (see /prices/[compound]
// robots). Derived from src/data/prices.index.json (generated by scripts/price-pull/
// to_prices.py) so it can't drift from the render's ≥3-vendor ungating threshold.
const priceIndex = require("./src/data/prices.index.json");
const noindexPricePaths = new Set(
  priceIndex.filter((p) => !p.indexable).map((p) => `/prices/${p.slug}`),
);
const PRICE_DETAIL = /^\/prices\/[a-z0-9-]+$/;
const NEWS_DETAIL = /^\/news\/[a-z0-9-]+$/;

// ── lastmod: PARTIAL, per-ENTITY data dates only (never a build-time or per-file git date) ──────
// autoLastmod stays FALSE. next-sitemap's autoLastmod:true stamps `new Date().toISOString()` — the
// BUILD TIME, identical on every URL, bumping on every deploy even when nothing changed. That trains
// Google to discount the signal and is strictly worse than nothing.
//
// A prior (Aug 2026) attempt used the git last-commit date of each route's source/data files. It was
// reverted because the dates were FLAT: the ~111 coupon+price pages all derive from the SHARED files
// vendors.ts / prices.generated.ts, so one pull re-dates them all at once, and any sitewide prose
// sweep re-dates every file it touches — ~5 distinct dates across 282 routes. Do NOT reintroduce a
// per-file git date.
//
// What we emit instead — ONLY where the date reflects a REAL change to that entity, sourced from
// build-visible data, so different pages carry genuinely different dates:
//   • /coupons/<vendor>   -> lastmodData.vendorPulled[vendor]   (that vendor's own price-pull date)
//   • /prices/<compound>  -> lastmodData.compoundPulled[compound] (MAX pull date over the vendors that
//                            render a row for it — the compound's freshest data)
//   • /news/<slug>        -> the article's publish date, parsed from news.ts
// Both maps come from docs/PP_PRICE_DATA_MASTER_v1.md via scripts/price-pull/to_prices.py (the doc's
// per-vendor `pulled:` dates), regenerated deterministically and drift-checked by check:prices-sync.
//
// EVERYTHING ELSE gets NO <lastmod>. Self-contained editorial pages (profiles/compare/guides) were
// intentionally left out: their only date source is the per-file git date, which the measurement above
// showed collapses under sweeps and needs a CI `git fetch --unshallow`. An absent lastmod is neutral;
// a fabricated one is corrosive. Partial coverage is the design, not a gap.
const lastmodData = require("./src/data/lastmod.generated.json");
const { vendorPulled = {}, compoundPulled = {} } = lastmodData;

// News publish dates: parsed from src/data/news.ts (the source of truth; no generated JSON). Each
// article's `date` is a human string ("August 8, 2026"); convert to ISO with an explicit month map so
// the value is timezone-independent (never Date.parse, which shifts across the UTC boundary). The regex
// pairs each `slug:` with the `date:` in the SAME object by refusing to cross another `slug:`.
const NEWS_TS = path.join(__dirname, "src", "data", "news.ts");
const MONTHS = { January: "01", February: "02", March: "03", April: "04", May: "05", June: "06",
  July: "07", August: "08", September: "09", October: "10", November: "11", December: "12" };
const newsDates = (() => {
  const src = fs.readFileSync(NEWS_TS, "utf8");
  const re = /slug:\s*"([^"]+)"(?:(?!slug:)[\s\S])*?date:\s*"([A-Za-z]+)\s+(\d{1,2}),\s*(\d{4})"/g;
  const map = {};
  let m;
  while ((m = re.exec(src))) {
    const [, slug, mon, day, year] = m;
    if (MONTHS[mon]) map[slug] = `${year}-${MONTHS[mon]}-${String(day).padStart(2, "0")}`;
  }
  return map;
})();

module.exports = {
  siteUrl: "https://profpeptide.com",
  generateRobotsTxt: true,
  trailingSlash: false,
  // autoLastmod: false stops next-sitemap injecting the build-time default. lastmod is added
  // per-entity in transform()/additionalPaths() — see the note above module.exports.
  autoLastmod: false,
  // changefreq + priority are DROPPED entirely (not set here, not returned below). Google ignores
  // both, and a uniform changefreq=daily is a false "everything changes daily" signal — same class
  // of noise as a build-time lastmod. Omitting the keys makes next-sitemap emit neither tag.
  exclude: [
    // Legacy /research and /research/* -> 301 redirect to /peptides/* (next.config.js).
    // Canonical lives at /peptides/<slug>, which IS included.
    "/research",
    "/research/*",
    // Per-route OG/Twitter image endpoints (belt-and-suspenders with transform()).
    "/*/opengraph-image",
    "/*/twitter-image",
    // Retired vendors -> 308 redirect to /coupons (next.config.js). Derived from
    // vendors.ts `retired: true` so this can't drift from the registry.
    ...retiredCouponPaths,
    // Design sandbox (noindex, dev-only preview) — never in the sitemap.
    "/prototype",
    "/prototype/*",
  ],
  transform: async (config, path) => {
    if (DROP_EXACT.has(path)) return null;
    if (DROP_PATTERNS.some((re) => re.test(path))) return null;
    // Price compound pages with <3 vendors are noindex -> keep them out of the sitemap.
    // /prices (master) and the ≥3-vendor compound pages pass through.
    if (PRICE_DETAIL.test(path) && noindexPricePaths.has(path)) return null;
    // Coupon detail pages come from the vendor registry (additionalPaths), not
    // the manifest — drop the manifest copy so inclusion is deterministic and
    // never duplicated.
    if (COUPON_DETAIL.test(path)) return null;
    // Per-entity lastmod (partial). Price pages -> the compound's freshest pull date; news -> publish
    // date. Absent from the map -> no <lastmod> (never a build-time date). No changefreq/priority.
    let lastmod;
    if (PRICE_DETAIL.test(path)) lastmod = compoundPulled[path.slice("/prices/".length)];
    else if (NEWS_DETAIL.test(path)) lastmod = newsDates[path.slice("/news/".length)];
    return { loc: path, ...(lastmod ? { lastmod } : {}) };
  },
  additionalPaths: async (config) => [
    // /peptides and /supplements USED to be re-added here: reading `?category` off searchParams
    // opted them into DYNAMIC (ƒ) rendering, so next-sitemap's manifest crawl (static ○ routes
    // only) missed them. The category filter is now client-side (HubCategoryBrowser), so both
    // hubs prerender ○ and enter the manifest on their own — the explicit re-add is gone.
    ...activeCouponSlugs.map((slug) => {
      // Coupon lastmod = that vendor's own price-pull date (absent -> no <lastmod>). No changefreq/priority.
      const lastmod = vendorPulled[slug];
      return { loc: `/coupons/${slug}`, ...(lastmod ? { lastmod } : {}) };
    }),
  ],
};
