// AUTO-GENERATED by scripts/check-vendors.mjs — do not edit by hand.
// Written only on a fully clean run (every active affiliate link reachable).
// This is the machine freshness stamp the coupon pages read for their Offer
// dateModified/validity and the "Verified <date>." line in meta descriptions.
// It attests the links were live on this date; it does NOT attest a code was
// tested at checkout (check-vendors cannot place an order).

/** ISO date of the last clean check:vendors run (affiliate links reachable). */
export const VENDORS_VERIFIED_ISO = "2026-08-01";

/** Human-readable form of {@link VENDORS_VERIFIED_ISO} for SERP-facing copy. */
export const VENDORS_VERIFIED_DATE = "August 1, 2026";
