// AUTO-GENERATED by scripts/check-vendors.mjs — do not edit by hand.
// Written on every run whose reachable set clears the >50% floor (so one dead vendor
// can't hold the freshness date hostage for the rest). A DEAD link is EXCLUDED from the
// verified set below and still fails the run (exit 1) so it gets fixed or the vendor retired.
// The date attests those links were live; it does NOT attest a code was tested at
// checkout (check-vendors cannot place an order). Codes are first-party (each vendor's
// own affiliate dashboard), so "verified and working" is what we can honestly claim.

/** ISO date of the last check:vendors run that cleared the floor. */
export const VENDORS_VERIFIED_ISO = "2026-09-02";

/** Human-readable form of {@link VENDORS_VERIFIED_ISO} for SERP-facing copy. */
export const VENDORS_VERIFIED_DATE = "September 2, 2026";

/** Vendor slugs actually verified (reachable, not DEAD) in that run. A coupon page must
 *  render its "verified" date ONLY if its slug is in this set — a vendor excluded from
 *  the last run (dead link) must not claim a verification it didn't get. */
export const VENDORS_VERIFIED_SLUGS = ["99-purity-peptides","aero-peptides","alera-research","almighty-peptides","alpha-peptides","ameano-peptides","amino-club","amino-x","amp-peptides","ascension-peptides","athena-peptides","biocollex","biolongevity-labs","biopure-peptides","capstone-peptides","crush-research","ez-peptides","forge-performance-co","glacier-aminos","hydro-research","ignite-peptides","improved-peptides","integrative-peptides","ion-peptide","iron-peptides","la-peptides","legendary-peptides","level-up-peptides","licensed-peptides","limitless-biotech","midwest-peptide","mile-high-compounds","modern-aminos","moglabs","nextgen-peptides","nova-labs","nura-peptide","oasis-labs","orbitrex-peptides","order-my-peptides","paradigm-peptides","particle-peptides","peptide-giants","peptide-partners","peptides-gg","peptidology","purity-peptides","real-peptides","royal-peptides","science-based-peptides","spartan-peptides","swiss-chems","synthesis-peptides","treasure-coast-peptides","valkyrie-peptides","vital-core-research"];
